version: '3.4'

services:
  ui:
    build:
      context: .
      target: build
    restart: unless-stopped
    ports:
      - '3000:3000'
    environment:
      - NEXT_PUBLIC_WAS_URL
    extra_hosts:
      - 'host.docker.internal:host-gateway'
